/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.Gonzalo.Libreria.ui;

import java.awt.Component;
import java.util.List;
import javafx.scene.Parent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import me.Gonzalo.Libreria.dao.clases.Autor;
import me.Gonzalo.Libreria.dao.clases.Libro;
import me.Gonzalo.Libreria.dao.impl.AutorImpl;
import me.Gonzalo.Libreria.dao.impl.LibroImpl;
import me.Gonzalo.Libreria.dao.interfaces.AutorDao;
import me.Gonzalo.Libreria.dao.interfaces.LibroDao;

/**
 *
 * @author Gonzalo
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private AutorDao autorDao;
    private LibroDao libroDao;
    public static final int CREAR=0;
    public static final int MODIFICAR=1;
    private int operacion;

    /**
     * Creates new form FrmPrincipal
     */
    
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        this.operacion=operacion;
        autorDao = new AutorImpl();
        cargarLibro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        btnGesAutores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");

        jLabel1.setText("Titulo");

        jLabel2.setText("Categoria");

        jLabel3.setText("ISBN");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);

        btnAutores.setText("Autores");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnAutores);

        btnGesAutores.setText("Gestionar Autores");
        btnGesAutores.setToolTipText("");
        btnGesAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGesAutoresActionPerformed(evt);
            }
        });

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Categoria", "ISBN", "Autores"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN)
                            .addComponent(txtTitulo)
                            .addComponent(txtCategoria)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGesAutores)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGesAutores)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        DlgMovimientos dlgMovimientos = new DlgMovimientos(this, true);
        dlgMovimientos.setVisible(true);
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnGesAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGesAutoresActionPerformed
        DlgPuestos dlgPuestos = new DlgPuestos(this, true,DlgPuestos.CREAR);
        dlgPuestos.setVisible(true);
    }//GEN-LAST:event_btnGesAutoresActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this,"¿desea borrar al Autor", "Confirmacion",JOptionPane.YES_NO_CANCEL_OPTION);
        if(resultado == JOptionPane.YES_OPTION){
            int posicion = tblLibros.getSelectedRow();
            DefaultTableModel modelo = (DefaultTableModel)tblLibros.getModel();
            Libro libro = new Libro((int) modelo.getValueAt(posicion, 0).toString());
            autorDao.borrar(libro);            
            cargarLibro();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if(operacion  == CREAR){
            List<Libro> conta = libroDao.listar();            
            Libro libro = new Libro(conta.size()+1, txtTitulo.getText(), txtCategoria.getText(), txtISBN.getText(), )
            LibroDao libroDao = new AutorImpl();
            libroDao.guardar(libro);
            cargarLibro();
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(operacion < MODIFICAR){
            int posicion = tblLibros.getSelectedRow();
            Libro libro = new Libro(conta.size()+1, txtTitulo.getText(), txtCategoria.getText(), txtISBN.getText(), )
            AutorDao autorDao = new AutorImpl();
            autorDao.modificar(libro);
            cargarAutor();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGesAutores;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void cargarLibro() {
        List<Libro> libro = libroDao.listar();
        List<Autor> autor = autorDao.listar();
        DefaultTableModel modelo=(DefaultTableModel)tblLibros.getModel();
        modelo.getDataVector().clear();
        for(int i =0;i<libro.size();i++){
            modelo.addRow(new Object[]{libro.get(i).getNombre(),libro.get(i).getCategoria(), libro.get(i).getIsbn(), autor.get(i).getNombres()});            
        }
    }  
}
